sudo: required
services:
  - docker

before_install:
  - docker build -t laramieralph/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true laramieralph/docker-react npm run 
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-879664979864"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"